# For development purposes
version: '3'

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    env_file:
      .env
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      .env
