# Generated by Django 2.0 on 2017-12-30 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('passphrase', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_info', models.CharField(max_length=100)),
                ('expires', models.DateTimeField()),
                ('service_key', models.CharField(max_length=100)),
                ('blimp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Blimp')),
            ],
        ),
    ]
