# Generated by Django 2.0 on 2017-12-31 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='blimp',
            name='pagekite_secret',
            field=models.CharField(default='zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invite',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_invite', to='fleet.Blimp'),
        ),
        migrations.AddField(
            model_name='invite',
            name='used_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet.Blimp'),
        ),
    ]
