# Generated by Django 2.0 on 2018-12-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_auto_20180129_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blimp',
            name='pagekite_secret',
        ),
        migrations.RemoveField(
            model_name='blimp',
            name='passphrase',
        ),
        migrations.AddField(
            model_name='blimp',
            name='pagekite_secret_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
